routes/web.php
<?php

use App\Http\Controllers\Admin\ArticleController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\RatePostController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Dashboard\ArticleController as DashboardArticleController;

Route::get('/', [PostController::class, 'index']);
Route::get('/articles/{article}', [PostController::class, 'show'])->name('posts.show');

Route::post('ratings', RatePostController::class)->name('ratings.store');
Route::prefix('dashboard')->middleware(['auth'])->group(function(){
    Route::get('/', function () {
        return view('author-dashboard');
    })->name('dashboard');
    Route::resource('articles', DashboardArticleController::class)->names('author.articles');
});


Route::prefix('admin')->middleware(['auth'])->group(function(){

    Route::get('/', function () {
        return view('admin-dashboard');
    })->name('admin');

    Route::resource('articles', ArticleController::class);
});



require __DIR__.'/auth.php';

app/Models/Article.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Whtht\PerfectlyCache\Traits\PerfectlyCachable;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Article extends Model
{
    use HasFactory, PerfectlyCachable;
    protected $fillable = [
        'title',
        'slug',
        'contents',
        'publish_at',
        'status',
        'user_id'
    ];
    protected  $casts = [
        'publish_at' => 'datetime:Y-m-d h:i'
    ];
    public function scopePublished($query)
    {
        return $query->where('publish_at', '<=', now())->where('status', 1);
    }

    public function getIsPublishedAttribute()
    {
        return $this->publish_at <= now();
    }

    public function author()
    {
        return $this->belongsTo(User::class, 'user_id', 'id');
    }
    public function ratings()
    {
        return $this->hasMany(Rating::class);
    }

    public function calculateRatings($article = null)
    {
        if (!$article) {
            $article = $this;
        }
        $ratings = $article->ratings()->latest()->get();
        $ratingsCount = ceil($ratings->count() * 0.3);
        $first30Percent = $ratings->take($ratingsCount);
        $first30PercentAvg = $first30Percent->average('value');
        $otherPartsPercentAvg = $ratings->whereNotIn('id', $first30Percent->pluck('id'))->average('value') / 2;
        return ($first30PercentAvg + $otherPartsPercentAvg) / 2;
    }
}

app/Http/Controllers/Admin/ArticleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\ArticleStoreRequest;
use App\Http\Requests\Admin\ArticleUpdateRequest;
use App\Models\Article;
use Illuminate\Http\Request;

class ArticleController extends Controller
{
    public function index()
    {
        $articles = Article::skipCache()->paginate(5);
        return view('admin.articles.index')->with(['articles' => $articles]);
    }

    public function create()
    {
        return view('admin.articles.create');
    }

    public function store(ArticleStoreRequest $request)
    {
        try {
            $article = Article::create($request->validated());
        } catch (\Throwable $th) {
            report($th);
            return redirect()->back()->with('error',env('APP_DEBUG') == true ? $th->getMessage() : "An eror has occurred");
        }
        return redirect()->route('articles.edit', $article->id);
    }

    public function show(Article $article)
    {
        return view('admin.articles.edit')->with(['article' => $article]);
    }

    public function edit(Article $article)
    {
        return view('admin.articles.edit')->with(['article' => $article]);
    }

    public function update(ArticleUpdateRequest $request, Article $article)
    {
        try {
            $article->update($request->validated());
        } catch (\Throwable $th) {
            report($th);
            return redirect()->back()->with('error', env('APP_DEBUG') == true ? $th->getMessage() : "An eror has occurred");
        }
        return redirect()->route('articles.edit', $article->id);
    }

    public function destroy(Article $article)
    {
        if (request()->user()->cannot('delete', $article)) {
            abort(403);
        }
        $article->delete();
        return redirect()->route('articles.index')->with('success', 'Deleted Successfully');
    }
}

app/Http/Controllers/Dashboard/ArticleController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Http\Requests\Author\ArticleStoreRequest;
use App\Http\Requests\Author\ArticleUpdateRequest;
use App\Models\Article;
use Illuminate\Http\Request;

class ArticleController extends Controller
{
    public function index()
    {
        $articles = Article::skipCache()->where('user_id', auth()->id())->paginate(5);
        return view('author.articles.index')->with(['articles' => $articles]);
    }

    public function create()
    {
        return view('author.articles.create');
    }

    public function store(ArticleStoreRequest $request)
    {
        try {
            $article = Article::create($request->validated());
        } catch (\Throwable $th) {
            report($th);
            return redirect()->back()->with('error',env('APP_DEBUG') == true ? $th->getMessage() : "An eror has occurred");
        }
        return redirect()->route('author.articles.edit', $article->id);
    }

    public function show($id)
    {
        $article = Article::skipCache()->where('user_id', auth()->id())->findOrFail($id);
        return view('author.articles.edit')->with(['article' => $article]);
    }

    public function edit($id)
    {
        $article = Article::skipCache()->where('user_id', auth()->id())->findOrFail($id);
        return view('author.articles.edit')->with(['article' => $article]);
    }

    public function update(ArticleUpdateRequest $request, $id)
    {
        $article = Article::skipCache()->where('user_id', auth()->id())->findOrFail($id);
        try {
            $article->update($request->validated());
        } catch (\Throwable $th) {
            report($th);
            return redirect()->back()->with('error', env('APP_DEBUG') == true ? $th->getMessage() : "An eror has occurred");
        }
        return redirect()->route('author.articles.edit', $article->id);
    }

    public function destroy(Article $article)
    {
        if (request()->user()->cannot('delete', $article)) {
            abort(403);
        }
        $article->delete();
        return redirect()->route('author.articles.index')->with('success', 'Deleted Successfully');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/author/articles/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Articles') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <!-- Session Status -->
            @if(session()->has('error'))
               <div class="text-red-800 ">{{ session('error') }}</div>
            @endif

            <!-- Validation Errors -->
            <x-auth-validation-errors class="mb-4" :errors="$errors" />

            <div class="flex flex-col">
                <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
                    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                        <form action="{{ route('author.articles.store') }}" method="POST">
                            @csrf
                            <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                                <div class="mx-2">
                                    <x-label for="title" :value="__('Title')" />
                                    <x-input id="title" class="block mt-1 w-full" type="text" name="title"
                                        :value="old('title', $article->title ?? null)" required autofocus />
                                </div>
                                <div class="mx-2">
                                    <x-label for="slug" :value="__('Slug')" />
                                    <x-input id="slug" class="block mt-1 w-full" type="text" name="slug"
                                        :value="old('slug', $article->slug ?? null)" required autofocus />
                                </div>
                                <div class="mx-2">
                                    <x-label for="contents" :value="__('Contents')" />
                                    <textarea rows="10" cols="10" id="contents"
                                        class=" rounded-md shadow-sm border-gray-300 focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50 block mt-1 w-full"
                                        type="text" name="contents" required autofocus>{{ old('contents', $article->contents ?? null) }}</textarea>
                                </div>
                                <div class="mx-2">
                                    <x-label for="publish_at" :value="__('Publish date')" />
                                    <x-input id="publish_at" class="block mt-1 w-full" type="datetime-local" name="publish_at"
                                        :value="old('publish_at', $article->publish_at ?? null)" required autofocus />
                                </div>
                                <div class="mx-2 mt-3">
                                    <x-label for="status" :value="__('Active?')" />
                                    <x-input id="status" class="" type="checkbox" name="status"
                                        :value="old('status', $article->status ?? null)" autofocus />
                                </div>
                                <div class="mt-5 mx-2">
                                    <x-button class="ml-4">
                                        {{ __('Submit') }}
                                    </x-button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/author/articles/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Articles') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <!-- Session Status -->
            @if(session()->has('error'))
            <div class="text-red-800 ">{{ session('error') }}</div>
            @endif

            <!-- Validation Errors -->
            <x-auth-validation-errors class="mb-4" :errors="$errors" />

            <div class="flex flex-col">
                <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
                    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                        <form action="{{ route('author.articles.destroy', $article->id) }}" method="POST">
                            @csrf
                            @method('DELETE')
                            <x-button class="ml-4 bg-red-800">
                                {{ __('Delete') }}
                            </x-button>
                        </form>
                        <form action="{{ route('author.articles.update', ['article' => $article->id]) }}" method="POST">
                            @csrf
                            @method('PUT')
                            <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                                <div class="mx-2">
                                    <x-label for="title" :value="__('Title')" />
                                    <x-input id="title" class="block mt-1 w-full" type="text" name="title"
                                        :value="old('title', $article->title ?? null)" required autofocus />
                                </div>
                                <div class="mx-2">
                                    <x-label for="slug" :value="__('Slug')" />
                                    <x-input id="slug" class="block mt-1 w-full" type="text" name="slug"
                                        :value="old('slug', $article->slug ?? null)" required autofocus />
                                </div>
                                <div class="mx-2">
                                    <x-label for="contents" :value="__('Contents')" />
                                    <textarea rows="10" cols="10" id="contents"
                                        class=" rounded-md shadow-sm border-gray-300 focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50 block mt-1 w-full"
                                        type="text" name="contents" required
                                        autofocus>{{ old('contents', $article->contents ?? null) }}</textarea>
                                </div>
                                <div class="mx-2">
                                    <x-label for="publish_at" :value="__('Publish date')" />
                                    <x-input id="publish_at" class="block mt-1 w-full" type="datetime-local"
                                        name="publish_at"
                                        :value="old('publish_at', $article->publish_at->format('Y-m-d\TH:i') ?? null)"
                                        required autofocus />
                                </div>
                                <div class="mx-2 mt-3">
                                    <x-label for="status" :value="__('Active?')" />
                                   <input type="checkbox" name="status" id="status" @if(old('status', $article->status))  checked @endif>
                                </div>
                                <div class="mt-5 mx-2">
                                    <x-button class="ml-4">
                                        {{ __('Submit') }}
                                    </x-button>
                                </div>
                            </div>
                        </form>


                    </div>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/author/articles/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Articles') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <!-- This example requires Tailwind CSS v2.0+ -->
            <div class="flex flex-col">
                <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
                    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                        <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                            @if(session()->has('success'))
                                <div class="bg-green-800 font-extrabold ">{{ session('success') }}</div>
                            @endif
                            <table class="min-w-full divide-y divide-gray-200">
                                <thead class="bg-gray-50">
                                    <tr>
                                        <th scope="col"
                                            class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                            Title
                                        </th>
                                        <th scope="col"
                                            class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                            Author name
                                        </th>
                                        <th scope="col"
                                            class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                            is published
                                        </th>
                                        <th scope="col"
                                            class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                            Actions
                                        </th>

                                    </tr>
                                </thead>
                                <tbody class="bg-white divide-y divide-gray-200">
                                    @foreach ($articles as $article)
                                        <tr>
                                            <td class="px-6 py-4 whitespace-nowrap">
                                                <div class="text-sm text-gray-900">{{ $article->title }}</div>
                                            </td>
                                            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                                {{ $article->author->name ?? '-' }}
                                            </td>
                                            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                               @if($article->is_published)
                                                    <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
                                                        YES
                                                    </span>
                                               @else
                                                    <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-red-100 text-red-800">
                                                        NO
                                                    </span>
                                               @endif
                                            </td>
                                            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                                <a href="{{ route('author.articles.edit', $article->id) }}">Manage</a>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>

                            {!! $articles->links() !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>